### ISSUE TITLE
Disable shortcuts when PoE is not the active window.

### ISSUE THREAD

**Issue by josemariafs** [Kyusung4698/PoE-Overlay#10] opened 2020-01-07 03:06 UTC
F5 is a frecuent used key, a good key to go to your hideout... but if PoE-Overlay is executed, you cant use it out of PoE (refresh some webs for example).

**Comment by Kyusung4698** [comment] 2020-01-07 22:02
Sadly global shortcuts are global and every trigger will prevent all other system messages. The only way to do this would be a loop and check ~500ms or so if the active window has changed. Seems like a overkill for me.
My first though would be another hotkey to toggle all other hotkeys. What do you think?

**Comment by josemariafs** [comment] 2020-01-07 23:00
Maybe control+F5 or alt+F5 by default can mitigate the problem, nobody will know that when they are out of PoE the shorcut is running.

Ty for your fast check.

**Comment by zaafar** [comment] 2020-01-08 02:39
Well, before executing the steps required in the global shortcut you can always check it poe is in the foreground or not. So basically the global shortcut will trigger but it won’t do anything.

**Comment by Kyusung4698** [comment] 2020-01-08 04:13
> Well, before executing the automation steps required in the global shortcut you can always check it poe is in the foreground or not. So basically the global shortcut will trigger but it won’t do anything.

That's true. But as long as I got a global shortcut registered - no other applications is able to listen to that key. So the key will be useless in all other applications.

**Comment by zaafar** [comment] 2020-01-08 08:35
-> But as long as I got a global shortcut registered  no other applications is able to listen to that key

Is that intentional? Which lib are you using to register the global hooks? I wonder if there is a param/flag/return type to enable/disable this.

**Comment by Kyusung4698** [comment] 2020-01-08 08:49
> -> But as long as I got a global shortcut registered no other applications is able to listen to that key
> 
> Is that intentional? Which lib are you using to register the global hooks? I wonder if there is a param/flag/return type to enable/disable this.

Yes, this is intentional. I'm using Electron for this: https://electronjs.org/docs/api/global-shortcut
I've looked through the documentation and i can't seem to find a 'passive' mode. May create an issue on there github.

**Comment by Kyusung4698** [comment] 2020-01-08 09:08
I think we are down to three solutions:
1. Make all hotkeys changable (F7/F8, too) and let the user decide what uncommon hotkeys he'd like to use.
2. Create a hotkey which toggles all other hotkeys expect itself.
3. Add a background task to check if the active window has change and register/unregister hotkeys if so.

I'd prefer 3 but this may take some time to develop. I think I'll start with 1 and go to 3 once the main "issues" are fixed.

**Comment by Calyx-** [comment] 2020-01-08 10:48
I previously had the same issue with an Electron app, I ended up working on a C++ DLL using node-gyp.

There was some annoying issues with versions and using electron-rebuild, but I eventually had a built DLL which could send modifier status and a pressed keycode to the electron side without swallowing the event for everything else.

**Comment by zaafar** [comment] 2020-01-08 17:12
-> I think we are down to three solutions:
None, I think it’s a global-shortcut issue. Let’s try to get it resolved over there.

**Comment by Kyusung4698** [comment] 2020-01-08 18:20
> -> I think we are down to three solutions:
> None, I think it’s a global-shortcut issue. Let’s try to get it resolved over there.

That's true. Although i think it'll take Electron quite some time to develop that feature - if they agree to do so. And because of that there should be a workaround implemented in the meantime.

**Comment by Doctah** [comment] 2020-01-09 14:51
> -> I think we are down to three solutions:
> None, I think it’s a global-shortcut issue. Let’s try to get it resolved over there.

It's not an issue, it's the intended behavior. Global does mean global after all.

**Comment by bMiquelin** [comment] 2020-01-10 00:32
I think it may be possible to get the current process on foreground.
https://github.com/octalmage/active-window

**Comment by Calyx-** [comment] 2020-01-10 00:54
I've done a quick test with C++ message handling rather than the built in electron stuff.

You can find the code for the module here: 
  https://github.com/Calyx-/hotkeys
And a messy implementation on the fork I made: 
  https://github.com/Calyx-/PoE-Overlay/tree/hotkeys

It checks that PoE is the foreground window before checking the key events, and doesn't block any keys from any other window.
It also keeps track of modifier statuses, sends a JSON formatted key info object to a callback.

The implementation of checking the keys against a list of shortcuts is more annoying in the renderer side of things, but I managed to get a quick example going, probably a better way to code that part.

**Comment by Kyusung4698** [comment] 2020-01-11 10:00
This is resolved in 0.4.2. Thanks to @Calyx- .

**Closed by Kyusung4698** 2020-01-11 10:00 UTC
Labels: enhancement
