### ISSUE TITLE
CTRL-D Always gives error.

### ISSUE THREAD

**Issue by Hemical** [Kyusung4698/PoE-Overlay#491] opened 2020-03-27 08:27 UTC
For a couple of days now I've had this error on every item I want to price check.
The overlay always shows "No data found. An error occurred". Below this, it says "No results found. Check browser?" and when clicking this it does show results. It seems the module to show it in game in the overlay is no longer working for me.

I've tried to reinstall, run as admin, etc. to no success. 

Here's an image of what it looks like:
![overlay error](https://user-images.githubusercontent.com/53646658/77736823-2ff9b080-700d-11ea-9607-2a2f2a3c949b.png)

Any suggestions to make it work again?

**Comment by Kyusung4698** [comment] 2020-03-27 10:12
Duplicate of #468

**Closed by Kyusung4698** 2020-03-27 10:12 UTC
