### ISSUE TITLE
Overlay doeps not work on game relaunch

### ISSUE THREAD

**Issue by Dariisa** [Kyusung4698/PoE-Overlay#123] opened 2020-01-23 02:08 UTC
When closing and opening poe the overlay does not work until I close and then open it.

**Comment by Kyusung4698** [comment] 2020-01-23 19:23
Any specific error message? Or behaviour? Thanks for reporting! Also please make sure the game window is active. Otherwise the hotkeys are disabled.

**Comment by Dariisa** [comment] 2020-01-23 22:50
No specific behavior, game window is active but the overlay text in the bottom left doesn't show and the hotkeys don't work until the program is relaunched.

**Comment by Kyusung4698** [comment] 2020-01-31 00:06
Sorry, for the late response. I could not reproduce this bug. Is it still an issue for you? Also please make sure the version text is visible before using any hotkeys. Thanks for your patience.

**Comment by Kyusung4698** [comment] 2020-02-08 14:12
I'll close this issue for now. Feel free to reopen.

**Closed by Kyusung4698** 2020-02-08 14:12 UTC
Labels: question
