### ISSUE TITLE
All inquiries give "error occured".

### ISSUE THREAD

**Issue by rlo5ca** [Kyusung4698/PoE-Overlay#493] opened 2020-03-27 11:08 UTC
Item Inquiry errors.

When attempting inquiry of item by using CTRL+D, window pops up with item inquiry but offers no results to compare with, citing"No Data Found, No Results, Open in browser?"

This literally happens with anything item I try to get a value for.

**Expected behavior**
Item inquiries should populate data as expected.

## 🌍  Southern, MD, USA

- OS: Windows 10 Home 64bit
- Version:  0.6.14
Most current POE update.

**Comment by Kyusung4698** [comment] 2020-03-27 11:14
Hi, thanks for creating an issue. Duplicate of #468

**Closed by Kyusung4698** 2020-03-27 11:14 UTC
Labels: bug
