### ISSUE TITLE
Onslaught on kill not recognizing

### ISSUE THREAD

**Issue by ishinome** [Kyusung4698/PoE-Overlay#155] opened 2020-01-27 21:17 UTC
It seems that there are multiple options to choose from on trade website and this uses the wrong one.
```
Rarity: Rare
Foe Bane
Vaal Greatsword
--------
Two Handed Sword
Physical Damage: 55-113
Elemental Damage: 58-109 (augmented), 18-35 (augmented)
Critical Strike Chance: 5.00%
Attacks per Second: 1.30
Weapon Range: 13
--------
Requirements:
Level: 68
Str: 122
Dex: 104 (unmet)
--------
Sockets: R-R 
--------
Item Level: 86
--------
40% increased Global Accuracy Rating (implicit)
--------
+10 to Dexterity
Adds 58 to 109 Fire Damage
Adds 18 to 35 Cold Damage
+48% to Cold Resistance
25% chance to gain Onslaught for 4 seconds on Kill
Attacks with this Weapon Penetrate 5% Cold Resistance
99% increased Elemental Damage with Attack Skills
--------
Redeemer Item
--------
```
![image](https://user-images.githubusercontent.com/49497278/73214558-1fd36b00-415b-11ea-82e1-d2ae699d935c.png)

![image](https://user-images.githubusercontent.com/49497278/73214660-4c878280-415b-11ea-810c-f142fdd37a84.png)

**Comment by Kyusung4698** [comment] 2020-01-27 21:39
Matching of stats are based on their text values. Those two stats have exactly the same value. I don't think this is an intended behavior of the GGG Trade Api. This will probably be resolved in a future patch.

To resolve this there must be always user input...

**Comment by trimbe** [comment] 2020-01-31 03:08
I think this could be fixed fairly easily by creating a count group with each affix? 

This behavior has been around for probably the entire lifespan of official trade (certainly at least for a year), so it seems unlikely it'll be fixed by them any time soon.

**Comment by fatings** [comment] 2020-02-04 16:03
I understand the developer in saying this should be fixed on GGG's side, but would it be possible to have a SUM group if there's more than one match for a single mod? Ignoring Implicit, crafted, etc.

**Closed** 2020-03-21 09:59 UTC
Labels: wontfix
