### ISSUE TITLE
Suggestion: 

### ISSUE THREAD

**Issue by Latencyyy** [Kyusung4698/PoE-Overlay#517] opened 2020-03-30 02:40 UTC
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

I have come to your program from just a common macro with auto hot key (AHK) and when scrolling through your stash ingame on the AHK macro I could hover my mouse cursor over the center of the screen (above my character) and the game would not zoom in or out of my character while scrolling through my stash tabs, this difference is not a deal breaker for me what so ever, but I think it would be a nice addition.

**Additional context**

**Comment by Kyusung4698** [comment] 2020-03-30 09:40
Duplicate of #369

**Closed by Kyusung4698** 2020-03-30 09:40 UTC
Labels: enhancement
