### ISSUE TITLE
Force Escape macro support?

### ISSUE THREAD

**Issue by Byngalo** [Kyusung4698/PoE-Overlay#229] opened 2020-02-12 15:57 UTC
Will Force Escape Macro be added?

**Comment by Kyusung4698** [comment] 2020-02-12 18:53
Hmm. Do you mean this #209?

**Comment by Byngalo** [comment] 2020-02-13 23:11
Maybe...

**Comment by Norby93** [comment] 2020-02-17 00:36
> Hmm. Do you mean this #209?

yes.

**Comment by Kyusung4698** [comment] 2020-02-17 10:09
> > Hmm. Do you mean this #209?
> 
> yes.

Thanks. I'll close this now. Duplicate of #209

**Closed by Kyusung4698** 2020-02-17 10:09 UTC
Labels: question
