### ISSUE TITLE
Bug: Clipboard was empty.

### ISSUE THREAD

**Issue by Haurabe** [Kyusung4698/PoE-Overlay#177] opened 2020-02-01 19:36 UTC
I've been catching this error quite often lately. 
The "Restore Focus" function does not help.
Is there any way to fix this?
![error](https://user-images.githubusercontent.com/55963243/73597968-360a6e00-4543-11ea-962d-4bde714204c5.png)

**Comment by Kyusung4698** [comment] 2020-02-03 07:55
Please do not use the 'Restore Focus' function. It's mostly used for debugging. I'll remove it in the next version.
Also it would help if you could provide a way to reproduce this issue. And/Or add your system specifications. Thanks!

**Comment by Haurabe** [comment] 2020-02-03 11:03
> Please do not use the 'Restore Focus' function. It's mostly used for debugging. I'll remove it in the next version.
> Also it would help if you could provide a way to reproduce this issue. And/Or add your system specifications. Thanks!

Most often, this happens after alt + tab from the game to the browser or other program.
This doesn't always happen, but if it does, it usually doesn't help. We just have to wait. Over time, everything starts to work normally. But this time is always different, so this causes problems.
PC: 
Windows 10 Pro 1909
GeForce GTX 660 (Driver v. 441.87)
Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz
RAM - 8GB
SSD - Kingston A400 [SA400S37/240G]
Monitor - 1366 x 768, 60Hz

**Comment by Haurabe** [comment] 2020-02-04 09:21
Thank you very much for the update.
If the problem still appears again, I will write again.

**Comment by Haurabe** [comment] 2020-02-04 09:48
Alas, the problem still remains. At the same time, it appeared not even after alt+tab, but simply during the game.

**Comment by Haurabe** [comment] 2020-02-05 16:59
Alas, the problem is not to do anywhere.
That is, exactly a second ago I found out the price of one item, and clicked on another I already caught this error
At the same time, the game I'm not alt+tab.

**Comment by Medifri501** [comment] 2020-02-10 19:08
Having the same problem. Can't pinpoint when it happens just some time after playing the game. Tried Ctrl+C -> Ctrl+D and it evaluated the item. Guess this works as a temporary workaround. If i can provide any additional info I'd be glad to.

**Comment by fenume** [comment] 2020-02-11 04:51
Same problem: alt+g/ctrl+alt+g always trigger this error for me. alt+w/ctrl+alt+w works fine at same time.

**Comment by alexander888123** [comment] 2020-02-14 01:05
![Безымянный](https://user-images.githubusercontent.com/61032224/74492187-1d08a200-4edf-11ea-9f19-64f78e54be66.png)

the problem is

**Comment by Kyusung4698** [comment] 2020-02-17 16:55
## 0.5.17 (2020-02-16)

- update hotkeys to be non-passive

The hotkeys are non passive again and are blocking the game input. This should prevent any in-game action to happen before the item could be parsed. Please let me know if this helped with the issue.

**Comment by Ma3lstr0** [comment] 2020-02-20 01:35
Having the same problem. Cant use this overlay, coz error repeats all the time. Change bindings helps some times, some times not. Reset Zoom in tray dont help too. 
![Снимок экрана (100)](https://user-images.githubusercontent.com/61258256/74892328-5c7d3580-539a-11ea-8afa-d28d251af3e0.png)

**Comment by Kyusung4698** [comment] 2020-02-23 20:48
@Ma3lstr0 Thanks for your feedback! What keybindings do you use? There was a issue regarding the `ALT` modifier prior 0.5.20.

**Comment by Haurabe** [comment] 2020-02-26 09:15
> @Ma3lstr0 Thanks for your feedback! What keybindings do you use? There was a issue regarding the `ALT` modifier prior 0.5.20.

Fix didn't help.
The problem has not disappeared.
Version - 0.5.21
![image](https://user-images.githubusercontent.com/55963243/75329815-5fdc5980-5891-11ea-8beb-2e34bd7b4798.png)

**Comment by 1322837** [comment] 2020-02-26 11:40
Hey, I have the same problem. I have 2 keyboard layouts: russian and english. I noticed that this problem occurs when i launch poe-overlay or open the in-game browser feature with russian layot on. If i use the default browser, everything works fine. The problem fixes itself when i open settings and save them w/o making any changes. I hope this can help.

**Comment by MBoBr** [comment] 2020-03-12 16:02
Still a thing. The problem occurs if u launch either PoE or Overlay using non-eng keyboard layout. The POE-TradeMacro had the same problem for a while but they fixed it somehow.

**Comment by Kyusung4698** [comment] 2020-03-12 20:36
## 0.6.0 (2020-03-12)

- fix `Clipboard was empty` while using a non US/DEU keyboard layout (#177)

@MBoBr Thanks to you i could actually reproduce this issue. The used libray robotjs was not compatible with different keyboard layouts. Please let me know if it's working now! 👍

**Comment by 1322837** [comment] 2020-03-12 23:10
Works for me now. Thx for the fix!

**Comment by dydxo959** [comment] 2020-03-14 10:40
same problem in 0.6.2 version " Clipboard is empty. Please make sure the game is focused. "
Ctrl+@ / Alt+@ / Ctrl+Alt+@ not work (@ is D, F, W, X that i tried)

i7 4790k
msi 1070 TF
16g ram

using poe's language and poe overlay is english.ver  but client is kakao

**Comment by AveAlpha** [comment] 2020-03-15 17:58
Same issue over here, first time trying the tool and getting "Clipboward is empty. Please make sure the game is focused."

I'm using a German keyboard with an English (United Kingdom) language setting and Polish (Programmers keyboard) setting in Windows 10 Pro

i5 6600k 
MSI GTX 1070 (Driver Version: 442.59)
16GB RAM
1080p 144hz

**Comment by nogenem** [comment] 2020-03-19 23:38
It happens to me too... I have to press right alt + w to get "?" and your program keeps giving me that "Clipboard was empty" message and doesn't let me get the "?" in the POE chat... Its quite annoying... ;/

**Comment by Kyusung4698** [comment] 2020-03-21 10:48
> It happens to me too... I have to press right alt + w to get "?" and your program keeps giving me that "Clipboard was empty" message and doesn't let me get the "?" in the POE chat... Its quite annoying... ;/
> 
> I'm using a "Brazil ABNT QWERTY" layout...

Hi, could you provide a screenshot? I'm not sure what "?" means.

**Comment by nogenem** [comment] 2020-03-21 11:39
> Hi, could you provide a screenshot? I'm not sure what "?" means.

The interrogation key (?), like when u ask a question ... On my keyboard i need to press the right alt + W to get it, and then i get the "Clipboard was empty" message and the key press is blocked... 

Like in [this](https://imgur.com/a/XamzB3U) img, i try to press right alt + W and the alert message pops up and the (?) isn't writed to the chat...

**Comment by Kyusung4698** [comment] 2020-03-21 11:42
> Like in [this](https://imgur.com/a/XamzB3U) img, i try to press right alt + W and the alert message pops up and the (?) isn't writed to the chat...

Ah, gotcha! `ALT + W` is bound to the opens item in wiki function. You can change the shortcut at the settings > misc > open item in wiki.

**Comment by nogenem** [comment] 2020-03-21 11:52
> Ah, gotcha! `ALT + W` is bound to the opens item in wiki function. You can change the shortcut at the settings > misc > open item in wiki.

So... I already [had changed](https://imgur.com/a/MoiYxON) the `Open wiki` to `Alt + Shift + W`, but i was still getting the alert message... Then now i entered in the game and did some tests, and when i pressed `RIGHT ALT + W` the program was opening the `Open wiki external`, even tho the hotkey to it is `Ctrl + Alt + W` on the UI... I then changed it to `Alt + Shift + W` and now i can get the (?) using `Right Alt + W` ... 

Ty for the help.

**Comment by Kyusung4698** [comment] 2020-03-22 10:24
I'll close this issue for now. Please create a new issue if this is still not fixed. There has been many updates since then.

**Closed by Kyusung4698** 2020-03-22 10:24 UTC
Labels: bug, waiting for feedback
