### ISSUE TITLE
In-Game Browser - Close shortcut

### ISSUE THREAD

**Issue by fatings** [Kyusung4698/PoE-Overlay#222] opened 2020-02-11 10:36 UTC
Is it possible to have Esc or Space close the browser instead of having to click the X with the mouse?

**Comment by Kyusung4698** [comment] 2020-02-11 20:08
This was an intended behaviour but got removed by #162 . Seems like the hotkey system needs a rewrite 🚀

**Comment by fatings** [comment] 2020-02-11 20:28
Either that or, if possible, go for the probably quick workaround, put Esc to close the window.

**Comment by Kyusung4698** [comment] 2020-02-11 20:34
Unfortunately a quick workaround is not possible as the spacebar and esc are bound to the same "dialog closing" logic - There are also global hotkeys. So yeah.

The window management needs a refresh anyway to support some of the need features (undocking browser, input management etc). So seems like a good opportunity.

**Comment by Kyusung4698** [comment] 2020-02-16 17:06
## 0.5.17 (2020-02-16)

- add `escape` to close browser (#222)

**Closed by Kyusung4698** 2020-02-16 17:06 UTC
Labels: enhancement
