### ISSUE TITLE
Can't search item with higher stat than the item i owned

### ISSUE THREAD

**Issue by ngtrungkhanh** [Kyusung4698/PoE-Overlay#223] opened 2020-02-11 11:05 UTC
For example, when i crt+D on my Lion's Roar and checked at "21%more melee physical ...", i can see the price in trade. I can search for "15-30% more"  but i can't search for "22-30% more" or "15-18% more.
SR for my bad English.

**Comment by Kyusung4698** [comment] 2020-02-11 20:28
This is an intended behaviour. The min value will never be greater than the actual value and the max value will never be less than the actual value. This was built in to keep the scrolling mechanism simple. But there is a "Enable input of numeric values with keyboard" #152 planned which will not have this saftey mechanism.

I'll close this issue. But feel free to reopen if this is not what you want/expect.

**Closed by Kyusung4698** 2020-02-11 20:28 UTC

**Comment by DinoMC** [comment] 2020-03-19 03:02
I'd love for it to be possible with scrolling too, more handy than typing a number for me.
Maybe only allow it to go above the current value if holding CTRL while scrolling, for example?
Or adding it as a setting that's off by default.

I don't use max range, and it's possible to go back to the original value by pressing the scroll wheel, so it would still be simple without the limit, for my use case anyway.

**Comment by DinoMC** [comment] 2020-03-19 03:13
> 

I'd love for it to be possible with scrolling too, more handy than typing a number for me.
Maybe only allow it to go above the current value if holding CTRL while scrolling, for example?
Or adding it as a setting that's off by default.

I don't use max range, and it's possible to go back to the original value by pressing the scroll wheel, so it would still be simple without the limit, for my use case anyway.
