### ISSUE TITLE
Customized search with insertable name like in TM.

### ISSUE THREAD

**Issue by leet0rz** [Kyusung4698/PoE-Overlay#597] opened 2020-04-09 20:55 UTC
Think CTRL + i in the original trade macro, sometimes I am looking to price an item that I dont have and that is not possible to do with poe overlay as far as I know. The original trade macro has a CTRL + i function where you open it and write "Goldrim" and it'll show all the goldrims and their prices.

**Comment by Kyusung4698** [comment] 2020-04-18 09:52
Duplicate of #374

**Closed by Kyusung4698** 2020-04-18 09:52 UTC
Labels: enhancement

**Comment by leet0rz** [comment] 2020-04-18 11:50
Thanks, glad you know of it :)
