### ISSUE TITLE
Suggestion: Pseudo values for resistances, life, stats etc.

### ISSUE THREAD

**Issue by Rohatej** [Kyusung4698/PoE-Overlay#43] opened 2020-01-10 21:18 UTC
Would be very useful to have an option for price checking based on pseudo vaules.

Sometimes is more accurate to look for pseudo vaules, than looking for exact values of life , specific resistances, etc.

_for examle:_ 
Pricechecking boots with

Pseudo 80life (can be combined from lower flat life roll and strenght)
75% total elemental resistances (any resistance)
25+ % move speed

gives more realistic result, than looking for boots with exact life value with specific resistances
Especially at league start

**Comment by Kyusung4698** [comment] 2020-01-13 15:32
Duplicate of #7

**Closed by Kyusung4698** 2020-01-13 15:32 UTC
Labels: enhancement
