### ISSUE TITLE
An Error Occured.

### ISSUE THREAD

**Issue by Tittynope1** [Kyusung4698/PoE-Overlay#468] opened 2020-03-25 14:55 UTC
I keep getting an error when looking up its, I can open them up in the browser without an issue though.  Tried to reinstall, using the none setup version still the same issue.

# 🐞 bug report

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

## 🌍  Your Environment

- OS:  e.g. Win10 x64
- Version:  e.g. 0.6.12 setup version
- PoE:  e.g. Steam 3.10.0/f English

**Comment by Kyusung4698** [comment] 2020-03-25 16:35
Hi, thanks for creating an issue. Does this error occur on all items? Or only specific items? If so please provide example item data (CTRL + C). Thanks!

**Comment by Alfcam** [comment] 2020-03-25 18:02
I am having the same issue as Tittynope. It occurs on all items I tested, uniques, rares, currency, fossils, div cards, splinters, essences and maps.

**Comment by tc662** [comment] 2020-03-25 18:48
Same issue. I have it on all kind of items. Last version that worked is 0.6.9
No other versions since have worked, including the new 0.6.13
Here's a paste:

Rarity: Rare
Blight Hold
Conjurer Gloves
--------
Quality: +20% (augmented)
Energy Shield: 112 (augmented)
--------
Requirements:
Level: 69
Dex: 65
Int: 109
--------
Sockets: B-B-B-B 
--------
Item Level: 79
--------
+39 to Dexterity
+15 to Intelligence
+30 to maximum Energy Shield
53% increased Energy Shield
+44% to Fire Resistance
+28 to maximum Life (crafted)

**Comment by Kyusung4698** [comment] 2020-03-25 19:01
> Same issue. I have it on all kind of items. Last version that worked is 0.6.9
> No other versions since have worked, including the new 0.6.13
> Here's a paste:
> 
> ```
> Rarity: Rare
> Blight Hold
> Conjurer Gloves
> --------
> Quality: +20% (augmented)
> Energy Shield: 112 (augmented)
> --------
> Requirements:
> Level: 69
> Dex: 65
> Int: 109
> --------
> Sockets: B-B-B-B 
> --------
> Item Level: 79
> --------
> +39 to Dexterity
> +15 to Intelligence
> +30 to maximum Energy Shield
> 53% increased Energy Shield
> +44% to Fire Resistance
> +28 to maximum Life (crafted)
> ```

Hi, could you create short gif - showing the last state (searching, listings, analyze). I've tried the copied item and it worked. Although only one item has been returned. The 0.6.10 version got a fresh makeover the evaluate dialog. So i guess we are on the right track.

**Comment by tc662** [comment] 2020-03-25 19:27
> Hi, could you create short gif - showing the last state (searching, listings, analyze). I've tried the copied item and it worked. Although only one item has been returned. The 0.6.10 version got a fresh makeover of the evaluate dialog. So i guess we are on the right track.

Hi, here's a gif:

https://gyazo.com/f1794c917c6218fc794ecea9b9b4bd96

**Comment by Tittynope1** [comment] 2020-03-25 19:57
https://imgur.com/a/1MyoaqC

Here is what happens with every item no matter what, and like the guy above me showed in the gif.  You can do a browser lookup and it correctly displays the information you're looking for

**Comment by willmaticx** [comment] 2020-03-25 23:47
Same thing happening here. It's been happening for the last couple of days. I've received an auto-update during that time as well that didn't help.

**Comment by Harry-Pootha** [comment] 2020-03-26 01:57
On my system the same error occurs, albeit only for one item. Here is the export of the item:

Rarity: Magic
The Shaper's Amber Amulet of Expulsion
--------
Requirements:
Level: 54
--------
Item Level: 74
--------
+25 to Strength (implicit)
--------
+24% to Chaos Resistance
Gain 9% of Physical Damage as Extra Lightning Damage
--------
Shaper Item



I have found that the title/base of the item is read as "The Shaper". By default this is selected in the search query. Deselecting this attribute resolves the error. This can be seen in these images:

https://imgur.com/a/yl4spFq

**Comment by spluhvag** [comment] 2020-03-26 02:29
Same problem here, any item/currency I try to price check will give me "no data found, an error occurred" just as @Tittynope1 's gif shows

**Comment by vertex101** [comment] 2020-03-26 02:45
okay i have had the same issue when i was using this as it was my first time but for it to work right you need to close out of PoE Overlay and then right click the desktop icon and hit run as administrator and that fixed my issue it now shows the prices like its suppose to

**Comment by spluhvag** [comment] 2020-03-26 03:06
@vertex101 I ran it as admin, it did not change the error occurred issue

**Comment by Kyusung4698** [comment] 2020-03-26 22:16
> I have found that the title/base of the item is read as "The Shaper". By default this is selected in the search query. Deselecting this attribute resolves the error. This can be seen in these images:

@Harry-Pootha This was caused by a mismatched base item type. It's fixed with 0.6.14

----

I've added a more in depth logging in 0.6.14 and improved the error handling while searching for an item. If this still occurs please attach the application logs. They can be found at `%appdata%/poe-overlay/logs/main.log`. Thanks!

**Comment by spluhvag** [comment] 2020-03-26 22:39
@Kyusung4698 i continue to get the same error. here is my log

[main.log](https://github.com/Kyusung4698/PoE-Overlay/files/4390367/main.log)

**Comment by Kyusung4698** [comment] 2020-03-26 23:23
> @Kyusung4698 i continue to get the same error. here is my log
> 
> [main.log](https://github.com/Kyusung4698/PoE-Overlay/files/4390367/main.log)

Could you post the copied item data + screenshot of the item in the overlay. Thanks!

**Comment by spluhvag** [comment] 2020-03-27 00:03
Rarity: Currency
Exalted Orb
--------
Stack Size: 11/10
--------
Enchants a rare item with a new random modifier
--------
Right click this item then left click a rare item to apply it. Rare items can have up to six random modifiers. The item's Catalyst quality increases the chance of applying a modifier which matches the quality type. Removes 20% Quality applied by Catalysts on use.
Shift click to unstack.

https://i.imgur.com/EiTlRZY.jpg

Just price checking an exalt as example

**Comment by spluhvag** [comment] 2020-03-27 00:11
@Kyusung4698 

It is the same error regardless of item

**Comment by willmaticx** [comment] 2020-03-27 01:16
Error log attached. Still failing on every item I try and Ctrl+D on.
[main.log](https://github.com/Kyusung4698/PoE-Overlay/files/4390900/main.log)

**Comment by spluhvag** [comment] 2020-03-27 01:24
Ok I got this fixed, uninstall poe-overlay and delete the %appdata%/roaming/poe-overlay folder, reinstall the latest version and its all good

**Comment by tc662** [comment] 2020-03-27 07:15
> Ok I got this fixed, uninstall poe-overlay and delete the %appdata%/roaming/poe-overlay folder, reinstall the latest version and its all good

This has also fixed the issue for me, thank you.

**Comment by Hemical** [comment] 2020-03-27 10:23
> Ok I got this fixed, uninstall poe-overlay and delete the %appdata%/roaming/poe-overlay folder, reinstall the latest version and its all good

This does seem to solve the issue indeed, thanks for the share, good info for the developer.

**Comment by Kyusung4698** [comment] 2020-03-27 11:19
Hi, a quick follow up. This is related with poe.ninja. Somehow their requests do not return any information. By clearing the %appdata% folder the cache etc. gets removed and the requests seem to work again like normal. I'm adding some extra error handling around the poe.ninja calls. Hopefully this catches the error and i can debug further as i'm unable to reproduce this on my local system.

Also the evaluate part of the dialog did not work because it relies on the data given by poe.ninja to convert currencies. 

Thanks again for given me this feedback!

**Comment by rlo5ca** [comment] 2020-03-27 11:23
> Hi, a quick follow up. This is related with poe.ninja. Somehow their requests do not return any information. By clearing the %appdata%/roaming/poe-overlay folder the cache etc. gets removed and the requests seem to work again like normal. I'm adding some extra error handling around the poe.ninja calls. Hopefully this catches the error and i can debug further as i'm unable to reproduce this on my local system.
> 
> Also the evaluate part of the dialog did not work because it relies on the data given by poe.ninja to convert currencies.
> 
> Thanks again for given me this feedback!

Confirmed this works!!! Thank you! deleting the poe-overlay folder and relaunching did the trick. 
Working as expected again :)

**Comment by Tittynope1** [comment] 2020-03-27 11:50
Hi all latest up resolved the issue.  Thanks for making such a great app

**Comment by Kyusung4698** [comment] 2020-03-27 12:33
## 0.6.15 (2020-03-27)

- fix an error occured while fetching poe.ninja (#468)

**Comment by EpicFailTrain** [comment] 2020-03-29 08:24
Hi, this is still not working for me - I have installed the latest version and deleted the cache, relaunched, rebooted and still getting an error message:
![image](https://user-images.githubusercontent.com/62830467/77844462-dce15280-71f2-11ea-9725-00fe3b144019.png)

**Comment by EpicFailTrain** [comment] 2020-03-29 08:25
[2020-03-29 19:22:39.121] [info] App starting...
[2020-03-29 19:22:39.128] [info] App checking animation flag: false.
[2020-03-29 19:22:39.129] [info] App checking keyboard flag: false.
[2020-03-29 19:22:39.162] [info] App args []
[2020-03-29 19:22:39.164] [info] App served false
[2020-03-29 19:22:40.394] [info] Checking for update
[2020-03-29 19:22:40.503] [info] Generated new staging user ID: d6cd4fcc-1d33-5d6e-8fdb-b44875d84f20
[2020-03-29 19:22:42.414] [info] set bounds to:  { x: 0, y: 0, width: 1920, height: 1080 }
[2020-03-29 19:22:42.964] [info] Update for version 0.6.15 is not available (latest version: 0.6.15, downgrade is disallowed).
[2020-03-29 19:22:53.675] [warn] {
  error: { isTrusted: true },
  headers: { headers: {}, lazyUpdate: null, normalizedNames: {} },
  message: 'Http failure response for https://poe.ninja/api/data/itemoverview: 0 Unknown Error',
  name: 'HttpErrorResponse',
  ok: false,
  status: 0,
  statusText: 'Unknown Error',
  url: 'https://poe.ninja/api/data/itemoverview'
}
[2020-03-29 19:22:55.158] [warn] {
  error: { isTrusted: true },
  headers: { headers: {}, lazyUpdate: null, normalizedNames: {} },
  message: 'Http failure response for https://poe.ninja/api/data/currencyoverview: 0 Unknown Error',
  name: 'HttpErrorResponse',
  ok: false,
  status: 0,
  statusText: 'Unknown Error',
  url: 'https://poe.ninja/api/data/currencyoverview'

**Comment by Kyusung4698** [comment] 2020-03-31 20:46
@EpicFailTrain thanks for attaching the log. Could you please give the new version a try? Thanks!

**Comment by EpicFailTrain** [comment] 2020-03-31 23:21
Hi, not getting that error anymore, just getting no results found - opening in browser is working fine though
[main.log](https://github.com/Kyusung4698/PoE-Overlay/files/4411967/main.log)

**Closed** 2020-05-06 00:20 UTC
Labels: bug, waiting for feedback, wontfix
