### ISSUE TITLE
An error occurred.

### ISSUE THREAD

**Issue by dlowis** [Kyusung4698/PoE-Overlay#520] opened 2020-03-30 23:42 UTC
I go to search a unique. It comes up with baseline price, the small graph etc, but the different prices that pops up on bottom of the window shows "An Error Occurred". Relaunched poe and poeoverlay

**Comment by Dezlel** [comment] 2020-03-30 23:57
This is happening to me aswell, restarted poe and poeover lay still nothing :(

**Comment by cmihran** [comment] 2020-03-31 00:00
Same issue here.

**Comment by Keito719** [comment] 2020-03-31 00:10
Same for me.
![Annotation 2020-03-30 190154](https://user-images.githubusercontent.com/62915799/77973539-1c26a680-72ba-11ea-9b66-aa0f0b3c2671.png)

**Comment by thorsten-passfeld** [comment] 2020-03-31 01:22
Obviously it's because the trade site is down/incredibly slow.

**Comment by Keito719** [comment] 2020-03-31 03:30
> Obviously it's because the trade site is down/incredibly slow.

Lol of course it would be my luck to install this AS the trade site goes down. haha

**Comment by sephwalker56** [comment] 2020-03-31 06:08
Try using ipconfig /flushdns and/or restarting iexplore.exe

Flushing the DNS resolver cache seems to fix the problem for me, at least for a while. iexplore.exe restarting also fixed the problem for a short time. I don't have any issues connecting to or using any of the trade sites, yet PoE Overlay is still having this problem. I don't know if PoE Overlay even relies on iexplore.exe but it might and it did fix the problem, albeit temporarily. I just have a command prompt open ready to flush DNS anytime this happens. Really annoying. POE Trade Macro still works just fine, even when PoE Overlay doesn't. I'm guessing this is a bug within PoE Overlay, and not a problem with the trade sites (since other applications work fine, and the websites themselves work just fine).

**Comment by SinisterGenocide** [comment] 2020-03-31 06:49
just down graded to .6.10 version. works fine. been having issues with all version after this one. every time there is something wrong i downgrade to that one and it works fine again

**Comment by Kyusung4698** [comment] 2020-03-31 08:22
Hi, thanks for creating an issue.

> Try using ipconfig /flushdns and/or restarting iexplore.exe

Hm, @sephwalker56 may be on to something. Electron has it's own dns cache. As GGG tries to fix their API they probably updating their dns aswell - which results in this behavior. 

Also could you please attach the application logs? Thanks! They can be found at `%appdata%/poe-overlay/logs/main.log`.

**Comment by joe7dust** [comment] 2020-03-31 08:54
I can't think of a good reason why they'd be constantly changing their DNS servers. Also doesn't make sense that it would result in sporadic behavior like it is. Can get this error 2 or 3 times in a row then suddenly it will work.

It is happening to about half of all of my searches now, whereas I never even saw this message on 6.13 and older.

**Comment by Kyusung4698** [comment] 2020-03-31 09:15
> I can't think of a good reason why they'd be constantly changing their DNS servers. Also doesn't make sense that it would result in sporadic behavior like it is. Can get this error 2 or 3 times in a row then suddenly it will work.

Thank you for attaching your logs. It's not the DNS server changing. It's the actual server behind the domain that's is changing - a load balancer does this for example.

**Comment by joe7dust** [comment] 2020-03-31 09:18
> > I can't think of a good reason why they'd be constantly changing their DNS servers. Also doesn't make sense that it would result in sporadic behavior like it is. Can get this error 2 or 3 times in a row then suddenly it will work.
> 
> Thank you for attaching your logs. It's not the DNS server changing. It's the actual server behind the domain that's is changing - a load balancer does this for example.

I think the official site is actually having some sort of problem at the moment or they are rate limiting us. I keep getting "failed to fetch.. " on official site.

**Comment by sephwalker56** [comment] 2020-03-31 09:19
> 
> 
> I can't think of a good reason why they'd be constantly changing their DNS servers. Also doesn't make sense that it would result in sporadic behavior like it is. Can get this error 2 or 3 times in a row then suddenly it will work.
> 
> It is happening to about half of all of my searches now, whereas I never even saw this message on 6.13 and older.

I'm with this guy -- I also can't think of a single reason why this would be happening. I don't know enough about the various software to say with certainty, but I very much doubt that this is a problem caused by anything other than something that changed within PoE Overlay in this latest update. Given that the previous build versions apparently work fine, that both POE Trade Macro *and* the various trade websites also all work just fine in multiple browsers, yet PoE Overlay continually fails, all signs point to something going wrong with PoE Overlay.

That said, it is particularly bizarre that clearing Windows' DNS cache fixes it, although it's incredibly brief. 

Checking the log files myself, and I notice:

```
[2020-03-31 01:50:57.276] [warn] {
  error: { error: { code: 3, message: 'Rate limit exceeded' } },
  headers: { lazyUpdate: null, normalizedNames: {} },
  message: 'Http failure response for https://www.pathofexile.com/api/trade/fetch/6b834f2ca1ea8344e5650e9bf44671882c98c609043df12863050a5dbf7ba380,f6a8ffd27687c91421cb2ca7a1a03ae2e718415f9a35d2444265b01d1e2eee8d,ae68b398bcef479c3559752cfa9016e55b592d6da0ed484fa3039d1481664583,baab2713a41a6de39e6c5364784f5980e44870248dbe9b845cdb8623685c9bb5,00f38d64ab47d542b648d9e465e5d98e93cb08be96989620b1732f41ee1baf3e,bdd53db7faaa7e71013d7815ad3492a0b3fb09827f7a7c510a2e26ba33b8f542,922f73fbef5c18a4b4a24ad2b3ce08f0b1cd31c22ea81b3757796c5d43cceb8a,97463455dee46dc9ee127cec490470d58048bd77b15418cb5ea46e1b25eb63c1,8518dfd0d522a345d81117e3b1608a5054bd57eb950195baac00386a94ccd2a6,7016452b7656a1010b20752de56bf8f36c1e5f6dec28fd6b0cd6c048705559ad?query=yYz7QlltR: 429 OK',
  name: 'HttpErrorResponse',
  ok: false,
  status: 429,
  statusText: 'OK',
  url: 'https://www.pathofexile.com/api/trade/fetch/6b834f2ca1ea8344e5650e9bf44671882c98c609043df12863050a5dbf7ba380,f6a8ffd27687c91421cb2ca7a1a03ae2e718415f9a35d2444265b01d1e2eee8d,ae68b398bcef479c3559752cfa9016e55b592d6da0ed484fa3039d1481664583,baab2713a41a6de39e6c5364784f5980e44870248dbe9b845cdb8623685c9bb5,00f38d64ab47d542b648d9e465e5d98e93cb08be96989620b1732f41ee1baf3e,bdd53db7faaa7e71013d7815ad3492a0b3fb09827f7a7c510a2e26ba33b8f542,922f73fbef5c18a4b4a24ad2b3ce08f0b1cd31c22ea81b3757796c5d43cceb8a,97463455dee46dc9ee127cec490470d58048bd77b15418cb5ea46e1b25eb63c1,8518dfd0d522a345d81117e3b1608a5054bd57eb950195baac00386a94ccd2a6,7016452b7656a1010b20752de56bf8f36c1e5f6dec28fd6b0cd6c048705559ad?query=yYz7QlltR'
}
```

and many, many more just like this. I've attached the log file as well, and thank you for pointing out where that even was. But obviously, the notable content here is "rate limit exceeded."

I recall that one of the most recent changes was altering that timer from being a flat five seconds to being an adjustable timer. Digging into the settings, I turned up the timer to 2.5 seconds, and tested again. No more "An error occurred." I tested this by searching an item, and as soon as the results showed (which, they were significantly slower than normal, kinda sucks since one of the main advantages I see between PoE Overlay and the alternatives was the speed at which it found results) immediately started another search. After quite a few searches with no errors, I tested at 2 seconds, and now on occasion I received the error message.

So, conclusion, I'd say this is rate limiting done by PoEs trade site. A minimum of 2.5 seconds must pass between searches, else it will return an error. I'm curious if this could be bypassed by cycling between different search engines -- pathofexile.com, poe.trade, poeapp.com -- when PoE Overlay recognizes that a search is being done within that 2.5 second timespan (or, perhaps, a large time span as a just-in-case measure). 

On that note, a bit of a feature request that maybe doesn't belong right here but it's somewhat on topic, poeapp.com has a much, much nicer interface to work with than the alternatives (in my opinion) and it would be quite nice to be able to select within the options which site is opened when clicking the currency icon to open the search in browser. I despise POEs' web design and it's an absolute pain for me to use, personally.

Anywho, tl;dr: rate limiting is funtimes for everyone. Attached is a clean log demonstrating the error. 2.5s delay in settings resolves issue. I don't believe this has anything to do with DNS, and the DNS flush just incidentally helped because alt-tabbing and doing a flush was delaying the time between searches.
[main.log](https://github.com/Kyusung4698/PoE-Overlay/files/4407927/main.log)

**Comment by joe7dust** [comment] 2020-03-31 09:30
> > I can't think of a good reason why they'd be constantly changing their DNS servers. Also doesn't make sense that it would result in sporadic behavior like it is. Can get this error 2 or 3 times in a row then suddenly it will work.
> > It is happening to about half of all of my searches now, whereas I never even saw this message on 6.13 and older.
> 
> I'm with this guy -- I also can't think of a single reason why this would be happening. I don't know enough about the various software to say with certainty, but I very much doubt that this is a problem caused by anything other than something that changed within PoE Overlay in this latest update. Given that the previous build versions apparently work fine, that both POE Trade Macro _and_ the various trade websites also all work just fine in multiple browsers, yet PoE Overlay continually fails, all signs point to something going wrong with PoE Overlay.
> 
> That said, it is particularly bizarre that clearing Windows' DNS cache fixes it, although it's incredibly brief.
> 
> Checking the log files myself, and I notice:
> 
> ```
> [2020-03-31 01:50:57.276] [warn] {
>   error: { error: { code: 3, message: 'Rate limit exceeded' } },
>   headers: { lazyUpdate: null, normalizedNames: {} },
>   message: 'Http failure response for https://www.pathofexile.com/api/trade/fetch/6b834f2ca1ea8344e5650e9bf44671882c98c609043df12863050a5dbf7ba380,f6a8ffd27687c91421cb2ca7a1a03ae2e718415f9a35d2444265b01d1e2eee8d,ae68b398bcef479c3559752cfa9016e55b592d6da0ed484fa3039d1481664583,baab2713a41a6de39e6c5364784f5980e44870248dbe9b845cdb8623685c9bb5,00f38d64ab47d542b648d9e465e5d98e93cb08be96989620b1732f41ee1baf3e,bdd53db7faaa7e71013d7815ad3492a0b3fb09827f7a7c510a2e26ba33b8f542,922f73fbef5c18a4b4a24ad2b3ce08f0b1cd31c22ea81b3757796c5d43cceb8a,97463455dee46dc9ee127cec490470d58048bd77b15418cb5ea46e1b25eb63c1,8518dfd0d522a345d81117e3b1608a5054bd57eb950195baac00386a94ccd2a6,7016452b7656a1010b20752de56bf8f36c1e5f6dec28fd6b0cd6c048705559ad?query=yYz7QlltR: 429 OK',
>   name: 'HttpErrorResponse',
>   ok: false,
>   status: 429,
>   statusText: 'OK',
>   url: 'https://www.pathofexile.com/api/trade/fetch/6b834f2ca1ea8344e5650e9bf44671882c98c609043df12863050a5dbf7ba380,f6a8ffd27687c91421cb2ca7a1a03ae2e718415f9a35d2444265b01d1e2eee8d,ae68b398bcef479c3559752cfa9016e55b592d6da0ed484fa3039d1481664583,baab2713a41a6de39e6c5364784f5980e44870248dbe9b845cdb8623685c9bb5,00f38d64ab47d542b648d9e465e5d98e93cb08be96989620b1732f41ee1baf3e,bdd53db7faaa7e71013d7815ad3492a0b3fb09827f7a7c510a2e26ba33b8f542,922f73fbef5c18a4b4a24ad2b3ce08f0b1cd31c22ea81b3757796c5d43cceb8a,97463455dee46dc9ee127cec490470d58048bd77b15418cb5ea46e1b25eb63c1,8518dfd0d522a345d81117e3b1608a5054bd57eb950195baac00386a94ccd2a6,7016452b7656a1010b20752de56bf8f36c1e5f6dec28fd6b0cd6c048705559ad?query=yYz7QlltR'
> }
> ```
> 
> and many, many more just like this. I've attached the log file as well, and thank you for pointing out where that even was. But obviously, the notable content here is "rate limit exceeded."
> 
> I recall that one of the most recent changes was altering that timer from being a flat five seconds to being an adjustable timer. Digging into the settings, I turned up the timer to 2.5 seconds, and tested again. No more "An error occurred." I tested this by searching an item, and as soon as the results showed (which, they were significantly slower than normal, kinda sucks since one of the main advantages I see between PoE Overlay and the alternatives was the speed at which it found results) immediately started another search. After quite a few searches with no errors, I tested at 2 seconds, and now on occasion I received the error message.
> 
> So, conclusion, I'd say this is rate limiting done by PoEs trade site. A minimum of 2.5 seconds must pass between searches, else it will return an error. I'm curious if this could be bypassed by cycling between different search engines -- pathofexile.com, poe.trade, poeapp.com -- when PoE Overlay recognizes that a search is being done within that 2.5 second timespan (or, perhaps, a large time span as a just-in-case measure).
> 
> On that note, a bit of a feature request that maybe doesn't belong right here but it's somewhat on topic, poeapp.com has a much, much nicer interface to work with than the alternatives (in my opinion) and it would be quite nice to be able to select within the options which site is opened when clicking the currency icon to open the search in browser. I despise POEs' web design and it's an absolute pain for me to use, personally.
> 
> Anywho, tl;dr: rate limiting is funtimes for everyone. Attached is a clean log demonstrating the error. 2.5s delay in settings resolves issue. I don't believe this has anything to do with DNS, and the DNS flush just incidentally helped because alt-tabbing and doing a flush was delaying the time between searches.
> [main.log](https://github.com/Kyusung4698/PoE-Overlay/files/4407927/main.log)
> 
> (EDIT: Just wanted to say, my tone might seem rude, and if that's the case I want to make it clear that that's not my intent at all. I love this little piece of software and it's clear that a lot of love has been put into it. The interface alone is far superior to any of the alternatives, and while the software does have some kinks that need to be ironed out, and it's missing many of the features that the alternatives have, it quickly became my go-to for the user interface alone. So thank you very much for putting your time and effort into this wonderful software and I hope that you continue to enjoy working on this project. <3)

See my comment I added at the same time as you. I don't think this is app related.

**Comment by sephwalker56** [comment] 2020-03-31 09:37
> 
> 
> > > I can't think of a good reason why they'd be constantly changing their DNS servers. Also doesn't make sense that it would result in sporadic behavior like it is. Can get this error 2 or 3 times in a row then suddenly it will work.
> > 
> > 
> > Thank you for attaching your logs. It's not the DNS server changing. It's the actual server behind the domain that's is changing - a load balancer does this for example.
> 
> I think the official site is actually having some sort of problem at the moment or they are rate limiting us. I keep getting "failed to fetch.. " on official site.

Interesting. Don't all the other trade sites also grab from the official site's data, though? And if that's the case, why do they work perfectly fine? 

I absolutely could be wrong about the cause -- but everything seems to lead to it being app related. Why would PoE Trade Macro still function flawlessly? Perhaps it's doing something differently in case of POEs official site lagging up? Too much I don't know about how these systems work. But, I think I've provided all the input I can here, so I'll be off for now. Hopefully Kyusung can get it figured out. I'll keep an eye out for if Kyusung requests anything else.

**Comment by Kyusung4698** [comment] 2020-03-31 09:44
> I absolutely could be wrong about the cause -- but everything seems to lead to it being app related. Why would PoE Trade Macro still function flawlessly? Perhaps it's doing something differently in case of POEs official site lagging up? Too much I don't know about how these systems work. But, I think I've provided all the input I can here, so I'll be off for now. Hopefully Kyusung can get it figured out. I'll keep an eye out for if Kyusung requests anything else.

PoE TradeMacro uses the poe.trade website instead of the official API/ Website. GGG lowered the requests rates for their trade api. Unfortunately my app is currently hitting those rates and getting a large "off time". I'll release a new version soon with configurable fetch counts. The default value will be 30 items instead of the current 100 items. This will ensure that the rate will be okay.

**Comment by sephwalker56** [comment] 2020-03-31 09:52
> 
> 
> > I absolutely could be wrong about the cause -- but everything seems to lead to it being app related. Why would PoE Trade Macro still function flawlessly? Perhaps it's doing something differently in case of POEs official site lagging up? Too much I don't know about how these systems work. But, I think I've provided all the input I can here, so I'll be off for now. Hopefully Kyusung can get it figured out. I'll keep an eye out for if Kyusung requests anything else.
> 
> PoE TradeMacro uses the poe.trade website instead of the official API/ Website. GGG lowered the requests rates for their trade api. Unfortunately my app is currently hitting those rates and getting a large "off time". I'll release a new version soon with configurable fetch counts. The default value will be 30 items instead of the current 100 items. This will ensure that the rate will be okay.

Right on. Would it be a simple feat to also allow for selecting which site to use? If that's not something that's possible with ease, I'll put in for a separate ticket for the feature request.

**Comment by Kyusung4698** [comment] 2020-03-31 09:56
> Right on. Would it be a simple feat to also allow for selecting which site to use? If that's not something that's possible with ease, I'll put in for a separate ticket for the feature request.

It's nothing with ease, sadly. poe.trade does not support a rest api -  instead i'd need to parse the html response. also they do not use the same ids for their mods/ stats so a mapping is required.

**Comment by thorsten-passfeld** [comment] 2020-03-31 10:07
I don't see the benefit of downgrading to PoE.trade. It's really lagging behind the official trade site.

**Comment by joe7dust** [comment] 2020-03-31 10:13
I agree that poe.trade is kinda worthless these days. I was getting an error when trying to use the official site even though, so I don't blame the app here.

**Comment by sephwalker56** [comment] 2020-03-31 10:18
> 
> 
> > Right on. Would it be a simple feat to also allow for selecting which site to use? If that's not something that's possible with ease, I'll put in for a separate ticket for the feature request.
> 
> It's nothing with ease, sadly. poe.trade does not support a rest api - instead i'd need to parse the html response. also they do not use the same ids for their mods/ stats so a mapping is required.

I'm personally more interested in poeapp.com -- poe.trade kinda blows.

**Comment by Kyusung4698** [comment] 2020-03-31 10:25
> I'm personally more interested in poeapp.com -- poe.trade kinda blows.

poeapp seems nice. I'm currently trying to reach out to it's owner to ask for permission using the api an such and if he thinks he can handle the load.

**Comment by Kyusung4698** [comment] 2020-03-31 10:40
## 0.6.16 (2020-03-31)

- add configurable fetch count to ensure the request rate is met (#520)
- add clear session on application start and unknown http error (#520)

**Comment by sephwalker56** [comment] 2020-03-31 21:46
> 
> 
> > I'm personally more interested in poeapp.com -- poe.trade kinda blows.
> 
> poeapp seems nice. I'm currently trying to reach out to it's owner to ask for permission using the api an such and if he thinks he can handle the load.

Right on -- best of luck. It's quite nice, and very responsive. Hopefully he's willing to allow it.

**Comment by Kyusung4698** [comment] 2020-04-01 15:08
I'll close this issue for now. Seems like the trade api is stable again.

**Closed by Kyusung4698** 2020-04-01 15:08 UTC
