### ISSUE TITLE
Suggestion: would be nice to be able to dis-able num keys macros

### ISSUE THREAD

**Issue by ggrentz** [Kyusung4698/PoE-Overlay#573] opened 2020-04-05 06:31 UTC
i like to use my num keys when pricing items and some of them pull open web pages (neat feature, but would like to turn it off but cant find anywhere in settings)

**Comment by Kyusung4698** [comment] 2020-04-05 08:25
Duplicate of #362

**Closed by Kyusung4698** 2020-04-05 08:25 UTC
