### ISSUE TITLE
Suggestion: Adjust numbers higher than item's natural values (estimating before crafting)

### ISSUE THREAD

**Issue by tonpix** [Kyusung4698/PoE-Overlay#422] opened 2020-03-21 16:13 UTC
Sorry if I missed, but couldn't find answer in wiki. The thing is, I would often like to estimate value of item after crafting, e.g. after crafting additional resistance. Currently, scrolling the number is capped to what item has.

For example, item naturally has 60% total elemental resistance. I want to craft 20% fire resistance later, but how can I estimate value before crafting?

**Comment by Kyusung4698** [comment] 2020-03-22 12:55
Duplicate of #270

**Closed by Kyusung4698** 2020-03-22 12:55 UTC
Labels: enhancement
