### ISSUE TITLE
Searching for blight maps with Ctrl + D does not count the blight modifier

### ISSUE THREAD

**Issue by Rottenbeer** [Kyusung4698/PoE-Overlay#570] opened 2020-04-04 22:06 UTC
I noticed that I can not price blighted maps with Ctrl + D because the blighted modifier is missing:
https://i.imgur.com/4LhKZuO.jpg

I saw that you said I should include the implicit, but maybe you want to make the implicit selected automatically?
I guess you don't want to search for the base map if you pricecheck a blighted map?

## 🌍  Your Environment

- OS: Win 10 
- Version: 0.6.17
- PoE: Steam, 3.10, English

**Comment by Kyusung4698** [comment] 2020-04-04 22:28
Duplicate of #164

**Closed by Kyusung4698** 2020-04-04 22:28 UTC
Labels: bug
