### ISSUE TITLE
Suggestion: Add a force logout macro (alt+f4)

### ISSUE THREAD

**Issue by JettPanopio** [Kyusung4698/PoE-Overlay#565] opened 2020-04-04 17:48 UTC
It would be nice to be able to set a hotkey to force close the game.
If this is a feature already requested, then please ignore this.
Thank you for you hard work!

**Comment by Kyusung4698** [comment] 2020-04-04 18:20
Duplicate of #209

**Closed by Kyusung4698** 2020-04-04 18:20 UTC
Labels: enhancement
