### ISSUE TITLE
No currency, unable to evaluate item

### ISSUE THREAD

**Issue by kartelusm** [Kyusung4698/PoE-Overlay#534] opened 2020-03-31 21:00 UTC
The app was working until perhaps a couple of hours ago, but then, for some reason, all the currency listing from the settings menu disappeared.
I suspect this caused the inability to evaluate any item ingame.

OS is windows 7 Ultimate. 
![settings](https://user-images.githubusercontent.com/5999998/78074623-55871100-73a3-11ea-98e9-8fee5affbc33.JPG)
![ingame](https://user-images.githubusercontent.com/5999998/78074626-56b83e00-73a3-11ea-9ae8-1dcccb9e0b9c.JPG)

**Comment by Kyusung4698** [comment] 2020-03-31 21:05
Duplicate of #534

**Closed by Kyusung4698** 2020-03-31 21:05 UTC
Labels: bug
