### ISSUE TITLE
Feature: Adding Modfiers % which indicates, how good this legendary is rolled

### ISSUE THREAD

**Issue by C3ntraX** [Kyusung4698/PoE-Overlay#420] opened 2020-03-21 09:54 UTC
Hey Kyusung4698,

I have an idea for a feature to indicate, which price I should choose.
Every legendary item has some modifiers, which has a range "from" - "to".
Often there are multiple of such ranges.

Now the problem: Often I want to figure out, if the Item is rolled good or not, which is not directly seen in your overlay. 
My idea is, that you add a percentage of item perfection somthing like this example:

Legenday "A" has these modifiers:
+10 - 60 Mana
+25% - 40% lightning res

Legenday "A" is rolled like this:
+ 25 Mana
+ 35% lightning res

Now the app calculates this:
Mana: 
60 - 10 = 50
25 - 10 = 15
15 / 50 = 30%
lightning res: 
40 - 25 = 15
35 - 25 = 10
10 / 15 = 66.67%
 
Item rating: ((30+66.67)/2) = **48,335%** 

Conclution: YAY now I instantly now, this is a shitty rolled item and has definitly no extra value....
Maybe you could display the rating of the single calculations too.... if this won´t take to much space

What do you mean, do you like this idea and want to implement this ?
If you have any further questions, ask me :)

**Comment by Kyusung4698** [comment] 2020-03-21 10:40
Duplicate of #119

**Closed by Kyusung4698** 2020-03-21 10:40 UTC
