### ISSUE TITLE
GeForce Now

### ISSUE THREAD

**Issue by AntyfrizZz** [Kyusung4698/PoE-Overlay#306] opened 2020-03-14 06:32 UTC
Hi there,

I am playing in GeForce Now and the overlay wont popup. Can you add support for it?

Best Regards

**Comment by Kyusung4698** [comment] 2020-03-14 19:41
>> Cant be done since poe overlay doesnt have access to clipboard info

> Yes, basically this. The program uses the clipboard info in order to parse the item data. NVIDIA Geforce Now does not share this information because it's not a fully functional VM. This is understandable as the core focus of their service is on performance and therefore it's highly customized to reduce network traffic. I don't think this will ever be possible.

Duplicate of #278

**Closed by Kyusung4698** 2020-03-14 19:41 UTC
