### ISSUE TITLE
Failing to set price on item in stash

### ISSUE THREAD

**Issue by erocheleau** [Kyusung4698/PoE-Overlay#664] opened 2020-04-25 13:49 UTC
Everytime I try to set a price on an item while its in the stash, I see poe-overlay trying to set the price, but it ends up with no price set and the chat window open.

I have 0.6.25
Playing on windowed fullscreen.

**Comment by EhhNahNoMouse** [comment] 2020-04-26 06:09
Check out #629. There are a couple videos. Sounds like your issue ^_^

**Comment by Kyusung4698** [comment] 2020-04-27 09:41
Duplicate of #629

**Closed by Kyusung4698** 2020-04-27 09:41 UTC
