### ISSUE TITLE
Auto pricing issue

### ISSUE THREAD

**Issue by RooseLectum** [Kyusung4698/PoE-Overlay#572] opened 2020-04-04 23:56 UTC
# 🐞 bug report

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

## 🌍  Your Environment

- OS:  e.g. Win7 x64
- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

When you go to auto price an item in the stash it will click on the chatbox instead of typing the value of the selected item

**Comment by Kyusung4698** [comment] 2020-04-05 08:24
Duplicate of #489

**Closed by Kyusung4698** 2020-04-05 08:24 UTC
Labels: bug
