### ISSUE TITLE
Suggestion: Block input when scrolling through stash/vendor tabs

### ISSUE THREAD

**Issue by Severinus3** [Kyusung4698/PoE-Overlay#462] opened 2020-03-24 22:07 UTC
Hey, my problem is that when I ctrl + scroll through stash/vendor tabs, my character gets zoomed in/out if I have my mouse cursor anywhere but in inventory/stash. 
That didn't happen when I was still using poe trade macro, so I'd love if it could be done for this too. 

Solution:
Not sure how it's done in trade macro, but my guess how to do it: map ctrl + scroll to right/left arrow key while not letting the scroll itself get through.

My current workaround:
I'm currently thinking of using poe trade macro along with poe overlay JUST for that functionality, which feels bad lol.

Really enjoying the tool otherwise, great job~

**Comment by Kyusung4698** [comment] 2020-03-25 06:58
Duplicate of #369

**Closed by Kyusung4698** 2020-03-25 06:58 UTC
Labels: enhancement

**Comment by Severinus3** [comment] 2020-03-25 13:29
Oops sorry, I did ctrl + f "scroll" instead of "wheel" so I missed the post...

**Comment by Kyusung4698** [comment] 2020-03-25 13:40
> Oops sorry, I did ctrl + f "scroll" instead of "wheel" so I missed the post...

No problem. Glad you've been searching! :rocket:
