### ISSUE TITLE
Commands fail to check if clipboard was set

### ISSUE THREAD

**Issue by TheAssociated** [Kyusung4698/PoE-Overlay#95] opened 2020-01-16 11:58 UTC
When a command such as F5 for /hideout fails to set the clipboard text successfully, it will enter previously set text into chat instead, if present. 

Clipboard should be checked for successful change before entering contents into the game. (Or send keys instead of using clipboard)

**Comment by Kyusung4698** [comment] 2020-01-18 23:12
Should be fixed with 0.5.1. This was an unintended behaviour which was caused by reseting the clipboard state pre-command. Thanks for reporting!

**Comment by TheAssociated** [comment] 2020-01-19 10:51
Played around 4h with the new version and the problem didn't reoccur. Will keep an eye out for it though.

**Comment by Kyusung4698** [comment] 2020-01-19 19:35
Thanks for your feedback. I'll close this issue for now. Feel free to re-open if needed.

**Closed by Kyusung4698** 2020-01-19 19:35 UTC
Labels: bug, possible fixed
