### ISSUE TITLE
Items with no rolls ( Unique Items ) should not be affected by roll range %

### ISSUE THREAD

**Issue by TerohsLab** [Kyusung4698/PoE-Overlay#245] opened 2020-02-17 22:03 UTC
I'm using https://i.imgur.com/adZ7ClK.png as an example.

Nothing except strength and increased attack damage against bleeding enemies rolls on this item.

Yet i can still adjust all the ranges on all the other mods. That should not be a thing for usability purposes.

Also "attack damage against bleeding enemies" should be shown down below where strength is.

Using 0.5.17

**Comment by TerohsLab** [comment] 2020-02-17 22:05
Also assuming this effects all rare items with like +1 curse for example. Haven't tested it yet.

**Comment by Kyusung4698** [comment] 2020-02-19 19:03
Duplicate of #150

**Closed by Kyusung4698** 2020-02-19 19:03 UTC
