### ISSUE TITLE
Windows taskbar is hidden

### ISSUE THREAD

**Issue by Racounous** [Kyusung4698/PoE-Overlay#60] opened 2020-01-11 16:18 UTC
I am using version 0.4.3 of PoE-Overlay on Windows 10, with PoE (Steam) on windowed fullscreen mode.
When alt tabbed to other apps, the windows taskbar is missing, showing poe behind the other apps.
![Captura de Ecrã (34)](https://user-images.githubusercontent.com/59771397/72207133-af0b2e00-348d-11ea-935d-e2eecff6ca4c.png)

Pressing the windows key open up the taskbar only while the start menu is open. Closing poe-overlay resolves the problem. 
![Captura de Ecrã (37)](https://user-images.githubusercontent.com/59771397/72207135-b6323c00-348d-11ea-9533-f69cbf825c9a.png)

Restarting explorer.exe does not fix the issue.

Additionally, two small quirks that may already be reported:
Delve mods are not searchable and searching by  a mod seem to search the exact value and not a minimum or maximum (if you search a roll with a very large range it's very likely to not get any results)

![Captura de Ecrã (97)](https://user-images.githubusercontent.com/59771397/72207137-bf230d80-348d-11ea-9179-ec0ac38d8df3.png)

Thank you for your work, really looking forward for the future of this tool.

**Comment by Slurpp** [comment] 2020-01-12 09:55
I also have this issue with the latest version of windows 10 installed. I am loving the addon other than this issue, thank you!

**Comment by bMiquelin** [comment] 2020-01-12 16:17
The good thing is that we can see our Life/ES bar, so we can see if we are being killed

**Comment by Deop** [comment] 2020-01-17 16:18
Having the same issue

**Comment by Kyusung4698** [comment] 2020-01-22 07:09
This is currently an intended behavior. Used to create such an (fullscreen) overlay without beeing focusable. I'll investigate this in the near future as this requires quite some time to fix.

**Comment by Kyusung4698** [comment] 2020-01-23 21:28
## 0.5.5 (2020-01-23)
* add autohiding overlay if poe is not active (#60, #61, #122)

Please report back if this fixes your issues. Thanks for making this tool better! 🚀

**Comment by Racounous** [comment] 2020-01-24 00:56
The 0.5.5 update has solved my issue, however, searching (Ctrl+D) seems to sometimes fail with the message "clipboard text is empty, make sure the game is focused". Alt tabbing and returning or waiting a few seconds solves the issue. Thank for fixing this issue and for being so responsive to feedback.

**Comment by Slurpp** [comment] 2020-01-24 07:50
This fixed the issue. Been testing it for the last hour or so, amazing work & thank you for your hard work!

**Comment by Kyusung4698** [comment] 2020-01-24 15:07
Thanks for your feedback. I'll close this for now. @Racounous please create an issue if this message appears more frequently than before.

**Closed by Kyusung4698** 2020-01-24 15:07 UTC
Labels: bug, possible fixed
