### ISSUE TITLE
Suggestion: [Option] Remove Max value from item evaluation

### ISSUE THREAD

**Issue by TechTrooper** [Kyusung4698/PoE-Overlay#516] opened 2020-03-29 22:26 UTC
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

Whenever I'm trying to evaluate items, there's automatic max value input which can hide better and even possibly cheaper items from the search.

- e.g. I'm trying to evaluate ES ring with 89 total resistance and PoE-overlay suggests price of 20 chaos.
- PoE-overlay sets max search value for total resistance at 98%
- Turns out that if PoE-overlay looked past 98%, it would've found out that there was already better and cheaper rings available

**Describe the solution you'd like**
Add option to remove max values from item evaluation. Poe Trade Macro has this feature too.

**Comment by Kyusung4698** [comment] 2020-03-30 10:14
Duplicate of #502

**Closed by Kyusung4698** 2020-03-30 10:14 UTC
Labels: enhancement
