### ISSUE TITLE
Rendering Issues

### ISSUE THREAD

**Issue by HSniBBy** [Kyusung4698/PoE-Overlay#107] opened 2020-01-20 20:38 UTC
I am extremely enthusiastic about this tool but have problems there.
As you can see on the screenshot I have graphics problems and I don't know what that is, all my drivers on my PC are up to date, AHK is also up to date even if you are not using AHK.

Do you have any idea what the problem might be?

best regards
Dennis
![bug](https://user-images.githubusercontent.com/60115152/72756339-30209e80-3bcd-11ea-82ba-d120ee3635fa.JPG)

**Comment by Kyusung4698** [comment] 2020-01-20 22:43
This seems like a strange rendering bug to me.

Please post more details about your specs OS/CPU/GPU/RAM etc. For now there are some things you can try to fix this:

- Try updating/installing Google Chrome as Electron uses this and enable/disable hardware acceleration
- Try enabling DWM
- Try closing any other running App except PoE & Overlay

**Comment by HSniBBy** [comment] 2020-01-21 07:10
I use Windows 10 / AMD Ryzen 1700 / nividia gtx 1080 and have 16 GB DDR4 RAM

My standard browser is Opera, because Chrome is shit ^^

I switched hardware acceleration off and on again, but it didn't help either. I installed this electron, I think. DWM is activated.
I have no problems with Discord.
ps: I have exactly the same graphics problem with the poe Tool Exilence.
Unfortunately I am not a professional and I have never heard of some of the things they tell me. ^^

**Comment by Kyusung4698** [comment] 2020-01-21 08:28
Okay. So it's definitely a Chrome/Electron issue because Exilence uses the same. For now we can try to disable the gpu by doing so:
create a `run.bat` file with following content at the same directory as the .exe:
`start "" "poe-overlay 0.5.2.exe" --disable-gpu`
Please let me know if this helps! Thanks.

**Comment by HSniBBy** [comment] 2020-01-21 10:39
did I do something wrong? ^^
I have created a text document and have the command
start "" "poe-overlay 0.5.2.exe" --disable-gpu written into it and saved it as a run.bat file and packed this file in the folder where PoE overlay is. But when I run this file, an error message always appears.

![77](https://user-images.githubusercontent.com/60115152/72798017-706e3400-3c42-11ea-8439-56f1ad4a00fa.JPG)

**Comment by Kyusung4698** [comment] 2020-01-21 10:41
> did I do something wrong? ^^
> I have created a text document and have the command
> start "" "poe-overlay 0.5.2.exe" --disable-gpu written into it and saved it as a run.bat file and packed this file in the folder where PoE overlay is. But when I run this file, an error message always appears.
> 
> ![77](https://user-images.githubusercontent.com/60115152/72798017-706e3400-3c42-11ea-8439-56f1ad4a00fa.JPG)

You're probably using the 0.5.1 version. Just change "poe-overlay 0.5.2.exe" to "poe-overlay 0.5.1.exe" or whatever your .exe is called.

**Comment by HSniBBy** [comment] 2020-01-21 10:43
no i have 0.5.2^^
sorry for my missclick :D

**Comment by HSniBBy** [comment] 2020-01-21 11:30
unfortunately it does not work.
should I start "" "poe-overlay 0.5.2.exe" --disable-gpu just copy it into the bat files? and then start the .exe instead?

**Comment by sicu** [comment] 2020-01-21 11:32
> unfortunately it does not work.
> should I start "" "poe-overlay 0.5.2.exe" --disable-gpu just copy it into the bat files? and then start the .exe instead?

Try running the bat file regularly (not as admin). If you run it as admin with no directory structure specified in the bat file, windows will run it from Windows\system32 as you see from your screenshot.

**Comment by HSniBBy** [comment] 2020-01-21 11:53
OH! it works: D how awesome is that please ^^
is that a problem of mine? or can you possibly fix this in the future with an update?

**Comment by Kyusung4698** [comment] 2020-01-21 12:01
> OH! it works: D how awesome is that please ^^
> is that a problem of mine? or can you possibly fix this in the future with an update?

kinda. it's a chromium bug caused by mostly incompatible gpu drivers. it may or may not be fixed with a new electron version which provides a new chromium version. for the time being i may provide a version with disabled gpu acceleration by default or let the user decide. glad you got it working! 

> mega nice, best man
> keep it up, me and many other players would be very happy if we could use your tool for a long time.

thanks! make sure to spread the love ❤️

**Closed by Kyusung4698** 2020-01-21 12:01 UTC
Labels: bug

**Comment by HSniBBy** [comment] 2020-01-21 12:55
chrome? but I use Opera ^^
no idea then the problem is probably the same with Opera.
Yes, that would be great if you could do that. <3

**Comment by Kyusung4698** [comment] 2020-01-21 13:03
Electron uses Chromium (the browser engine of Chrome) to render the application. I'll add the .bat file for now.
