### ISSUE TITLE
Mod: Cannot Be Stunned

### ISSUE THREAD

**Issue by WhiteFang5** [Kyusung4698/PoE-Overlay#507] opened 2020-03-29 09:32 UTC
# 🛸 Item modifier report

**Current item modifier**
#% Chance To Avoid Being Stunned

**Expected item modifier**
Cannot Be Stunned

**Copied item data**

```
Rarity: Unique
Eye of Chayula
Onyx Amulet
--------
Requirements:
Level: 20
--------
Item Level: 79
--------
+12 to all Attributes (implicit)
--------
20% reduced maximum Life
30% increased Rarity of Items found
Cannot be Stunned
--------
Never blinking, always watching.

This item can be transformed with a Blessing of Chayula
```

## 🌍  Your Environment

- Version: 0.6.15

**Comment by Kyusung4698** [comment] 2020-03-30 10:14
Duplicate of #498

**Closed by Kyusung4698** 2020-03-30 10:14 UTC
Labels: mod
