### ISSUE TITLE
Suggestion: PoeTradeMacro "Find similar items" command

### ISSUE THREAD

**Issue by qwak-adikt** [Kyusung4698/PoE-Overlay#511] opened 2020-03-29 15:13 UTC
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

PoeTradeMacro had the option to create a hotkey, e.g. F1, and it would take the base item name (e.g., Viridian Jewel, Hubris Circlet, Breachstone) and would copy/paste whatever that information was into the stash search 
**Describe the solution you'd like**

Imitate the behavior to copy/paste search base item into the stash search bar
**Describe alternatives you've considered**

Running poetrademacro still
**Additional context**

Allows you to find all e.g. Diamond Rings in a dump tab for recipes, etc

**Comment by Kyusung4698** [comment] 2020-03-30 09:54
Duplicate of #293

**Closed by Kyusung4698** 2020-03-30 09:54 UTC
Labels: enhancement
