### ISSUE TITLE
Having big issues setting prices. Keeps trying to use chat?? Video included

### ISSUE THREAD

**Issue by ost3g0** [Kyusung4698/PoE-Overlay#649] opened 2020-04-20 17:12 UTC
Windows 10 64bit
Running ultra wide 1440p if it matters

When I try to set prices some items simply do not comply.  They keep failing over and over and over.

https://www.youtube.com/watch?v=t2l5k4vRQ24

Recorded video its easier to just see.

This happens very often for me. What's odd is some items simply work, but others refuse.

 Cant tell you what version my overlay is since it does not seem to show it anywhere? It auto updates so I'm guessing the latest??

**Comment by EhhNahNoMouse** [comment] 2020-04-21 04:56
Looks like bug #629. There's also a video on that one if you want to take a look. Onfire7 may have found the cause.

**Comment by Kyusung4698** [comment] 2020-04-22 11:36
Duplicate of #629

**Closed by Kyusung4698** 2020-04-22 11:36 UTC
Labels: bug
