### ISSUE TITLE
Using ctrl+scroll wheel changes camera zoom.

### ISSUE THREAD

**Issue by Sjatar** [Kyusung4698/PoE-Overlay#691] opened 2020-05-07 13:02 UTC
When scrolling through stash with ctrl+MW if not hovering over a inventory the scroll wheel will still scroll in and out the camera. 

Coming from trade macro this was not the case there. Might be possible to mute the scroll wheel output when holding ctrl and having the game in focus.

**Comment by Kyusung4698** [comment] 2020-05-08 14:23
Duplicate of #369

**Closed by Kyusung4698** 2020-05-08 14:23 UTC
Labels: bug
