### ISSUE TITLE
can't set price with premium tab !

### ISSUE THREAD

**Issue by mrzever** [Kyusung4698/PoE-Overlay#629] opened 2020-04-14 12:00 UTC
**Describe the bug**
Hello, i'm using poe overlay since a week or 2, you done great job btw !  i've always occuring an error when setting price on item, it just opening chat box and spamming my right click for a second. sometime all works fine but since 1 or 2 update the bug occurs more often ..tab are premium and set on individuallly priced. at the end the chat box is open and the mouse is on the top left corner of the screen 
thank you for reading !

## 🌍  Your Environment

- OS: <!-- ✍️ win 10 64b
- Version: <!-- 0.6.22 
- PoE: <!-- nosteam version 3.10.1c English

**Comment by Anastassia90210** [comment] 2020-04-16 02:58
I have been having the EXACT same problem!

**Comment by Orbitok** [comment] 2020-04-16 17:11
Same thing, 50% of the time can't set the price, send's you to the chat box, quite annoying.

**Comment by Orbitok** [comment] 2020-04-16 17:14
But if you change the item's location ( just move to any other free space in the same tab) it sets the price without problem. This also works 50% of the time =)

**Comment by EhhNahNoMouse** [comment] 2020-04-18 14:52
Seems like this may be a similar issue or result as bug #386, which for me is still occurring.
Video of issue: https://gfycat.com/revolvingnearbrahmanbull

**Comment by Kyusung4698** [comment] 2020-04-18 16:06
> Seems like this may be a similar issue or result as bug #386, which for me is still occurring.
> Video of issue: https://gfycat.com/revolvingnearbrahmanbull

Thanks for the video. I've got some questions for you to hopefully pin this issue down. 

- What OS are you using?
- What's your screen resolution? (Windows, PoE)
- What's the final position of the mouse? (It's unfortunately out of this video)
- Do you use Windows scaling and/or PoE Overlay zoom?
- Is PoE in windowed mode or windowed mode fullscreen?

Thanks in advance! 🚀

**Comment by Kyusung4698** [comment] 2020-04-18 18:55
## 0.6.23 (2020-04-18)

- fix mouse position incorrect applied after changing window display settings (#629)

**Comment by mrzever** [comment] 2020-04-18 20:11
> 
> 
> Seems like this may be a similar issue or result as bug #386, which for me is still occurring.
> Video of issue: https://gfycat.com/revolvingnearbrahmanbull

this is exactly that !
if it can help 

    What OS are you using? w10 64bits ver 18362
    What's your screen resolution? on windows 1920*1080 dual screen, poe 1920*1080 windows fullscreen (left screen)
    What's the final position of the mouse? just above "global" in the chat box
    Do you use Windows scaling and/or PoE Overlay zoom? nop as i know 
    Is PoE in windowed mode or windowed mode fullscreen? windowed fullscreen

**Comment by Kyusung4698** [comment] 2020-04-18 20:28
@mrzever thanks for your answer! Unfortunately i can't see any abnormalities. Can you please check if you're using mouse acceleration? And if so please try turning it off and report back. Thanks!

**Comment by EhhNahNoMouse** [comment] 2020-04-19 08:58
> 
> 
> > Seems like this may be a similar issue or result as bug #386, which for me is still occurring.
> > Video of issue: https://gfycat.com/revolvingnearbrahmanbull
> 
> Thanks for the video. I've got some questions for you to hopefully pin this issue down.
 
>What OS are you using?

Windows 10 Home x64 ver. 1903 build 18362.778
>What's your screen resolution? (Windows, PoE) 

Dual monitor - 1st Internet, 2nd POE: Both displays @1680x1050 (their native rez.)- POE is set to the same, windowed fullscreen. vsync enabled
>What's the final position of the mouse? (It's unfortunately out of this video) 

* The same position as it was when when Ctrl - D triggered the popup. 
* The video shows the starting cursor position @~2-3 seconds, the pop-up, clicking the popup bar graph, and @~8 seconds the cursor back at where it was @2-3 seconds. 
* If you want, when playing back the video, you can take your own cursor and place it over the one in the video to keep track of the starting position and notice that it snaps back to the starting position after clicking the graph. 

>Do you use Windows scaling and/or PoE Overlay zoom? 

Nope
>Is PoE in windowed mode or windowed mode fullscreen? 

Windowed fullscreen

 Thanks in advance! 🚀

Note: Also tried your suggestion to mrzever and duplicated the issue with the applications' hardware acceleration and windows' hardware acceleration (Mouse Properties -> Pointer Options -> Motion: [ ] Enhance pointer precision) turned off.

**Comment by mrzever** [comment] 2020-04-19 11:40
> 
> 
> @mrzever thanks for your answer! Unfortunately i can't see any abnormalities. Can you please check if you're using mouse acceleration? And if so please try turning it off and report back. Thanks!

it was already uncheck, can i check something else or record a small video ? (which program should i use?) 
and the 6.23 patch doesn't fix at all this problem 
Do you use Windows scaling and/or PoE Overlay zoom? where can i check this ? 
also when in full screen , ctrl + D on item open a window in windows screen and seems buggy and lock poe tab until i close the research window

**Comment by EhhNahNoMouse** [comment] 2020-04-19 16:38
> it was already uncheck, can i check something else or record a small video ? (which program should i use?)

There is probably something cooler/better?, but I used the program from here: https://www.cockos.com/licecap/ to capture mine. It's dirt simple, does the job.

**Comment by Onfire7** [comment] 2020-04-20 03:01
I am also having this issue. Windows 10 Pro, Dual Monitors, 1920x1080, Windowed Fullscreen, Dual Xeon X5660 @ 2.80 GHz, 48Gb RAM.

I really feel like this isn't a cursor position issue, but an input speed issue/race condition issue. I'm running on a server with dual Xeons and 48Gb of ram and it hasn't worked a single time for me. I am thinking that on faster computers with lower loads PoE-Overlay can input keyboard/mouse commands faster then PoE can process them and so sometimes they happen out of order.

I'm building it now to do some testing.

**Comment by EhhNahNoMouse** [comment] 2020-04-20 03:32
> 
> 
> I am also having this issue. Windows 10 Pro, Dual Monitors, 1920x1080, Windowed Fullscreen, Dual Xeon X5660 @ 2.80 GHz, 48Gb RAM.
> 
> I really feel like this isn't a cursor position issue, but an input speed issue/race condition issue. I'm running on a server and it hasn't worked a single time for me. I am thinking that on faster computers with lower loads PoE-Overlay can input keyboard/mouse commands faster then PoE can process them and so sometimes they happen out of order.
> 
> I'm building it now to do some testing.

On my system, if I turn on windows step recorder it seems to work correctly every time. Maybe that speaks to your theory.

**Comment by Onfire7** [comment] 2020-04-20 03:51
Ok, so, adding a 100 ms delay after the game focus seems to have fixed the issue for me. I'll submit a PR.

**Comment by Sathorn** [comment] 2020-04-20 10:14
I do have the same problem
I also have a dual monitor setup, 21:9 ratio has the one I am playing PoE, maybe this is important...

**Comment by Kyusung4698** [comment] 2020-04-22 14:19
## 0.6.24 (2020-04-22)

- fix mouse clicks not registering for price tagging (#629)

@Onfire7 thanks for your fix. The new version has now been released.

**Comment by mrzever** [comment] 2020-04-22 16:34
> 
> ## 0.6.24 (2020-04-22)
> 
>     * fix mouse clicks not registering for price tagging (#629)
> 
> 
> @Onfire7 thanks for your fix. The new version has now been released.

still having the issue on 0.6.24. i record a gif in case of 
gif  : https://gfycat.com/briefonlyamericanalligator

edit : at the end the mouse stop just where the item was in my storage

**Comment by EhhNahNoMouse** [comment] 2020-04-22 18:13
I am still having the issue as well.

**Comment by Onfire7** [comment] 2020-04-23 00:43
Dang, I'll try to look into it again on Friday. I had a feeling it might be racing in a couple of different places, this was just the one that seemed to fix it for me, so I was hoping that it would work for everyone... :/

**Comment by Kyusung4698** [comment] 2020-04-23 09:26
Thanks for your feedback. It seems like the mouse position is correct. So this issue has been resolved. I think the mouse click which triggers the fast tagging is also send to PoE which will then close the stash tab because it's not over the stash or inventory. Normally the overlay should block the mouse event.

Are you guys playing with hardware acceleration enabled? And do you have focusable enabled?

**Comment by EhhNahNoMouse** [comment] 2020-04-23 14:48
I tried reproducing the problem with different configurations of hardware acceleration and focusable. The problem occurred 100% of the time with all combinations that I tried. Combinations are listed below:

- Hardware Acceleration - PoE_Overlay - HW_PoE
- Hardware Acceleration - Windows 10 (Enhance Pointer Precision) - HW_Sys
- Focusable - F
--------------------------------------------
- HW_PoE - On
- HW_Sys - On
- F - On
---
- HW_PoE - On
- HW_Sys - On
- F - Off
---
- HW_PoE - Off
- HW_Sys - On
- F - Off
---
- HW_PoE - Off
- HW_Sys - On
- F - On
---
- HW_PoE - On
- HW_Sys - Off
- F - On
---

Notes: 
1. During the tests, there was not a single success. 
2. I tried using window's built in "Steps Recorder" to record my clicks and the problem did not occur. Fast Tagging was successful 10/10 tries.

**Comment by Kyusung4698** [comment] 2020-04-23 16:28
@EhhNahNoMouse thanks! Another question - If you enable/ disable a stat while the evaluate dialog is not over the stash/ inventory does this also close those windows?

**Comment by EhhNahNoMouse** [comment] 2020-04-24 01:04
![Disable_stat](https://user-images.githubusercontent.com/63628669/80164012-b5c93700-858c-11ea-8e0f-030cdcebb02e.gif)

It does not close the windows if I'm thinking about the correct thing. See video/gif above.

**Comment by Kyusung4698** [comment] 2020-04-24 14:27
## 0.6.25 (2020-04-24)

- add delay after closing the dialog via fast tagging (#629)

**Comment by EhhNahNoMouse** [comment] 2020-04-24 15:16
The issue is still occurring 100% of the time when I'm playing normally. When I'm recording the issue, it seems to be about 50% of the time (before when recording, it was 100%).

https://gfycat.com/beneficialpinkechidna

**Comment by Kyusung4698** [comment] 2020-04-27 09:45
@EhhNahNoMouse are you up to a remote debug session? I'm unable to reproduce this issue locally so all i can do is guessing what's causing this.

**Comment by mrzever** [comment] 2020-04-27 10:19
if i could help i can give you temporary access to mine, via teamviewer or parsec
but i'm not sure about all settings you said, mouse acceleration is off i'm sure about it but the rest .. all poe overlay settings are to their initial value i think
let me know if needed

**Comment by EhhNahNoMouse** [comment] 2020-04-27 14:31
Sure, that sounds fine. If you haven't already gotten what you need from mrzever, I'm also willing.

**Comment by erocheleau** [comment] 2020-04-27 19:16
I am also having this issue. Windows 10, Dual Monitors, 1920x1080, Windowed Fullscreen, RTX 2070, AMD Ryzen 5 3600x @3.80 GHz, 32Gb RAM.

I will test tonight, but one thing is that when the issue started appearing is I switched from Steam version to standalone version.

(Well along with building an entirely new PC xD)

**Comment by EhhNahNoMouse** [comment] 2020-04-27 21:38
I'm using the steam version.
Intel i7-7700K @4.20GHz, 1680x1050 Dual Monitor Win 10, Windowed Full. Nvidia GeForce GTX 1080

**Comment by jforeman56** [comment] 2020-04-28 03:40
I was also experiencing the same issue.  I disabled hardware acceleration in the overlay and it seems to have resolved the issue for me.

**Comment by EhhNahNoMouse** [comment] 2020-04-28 05:47
It appears that the hardware acceleration selection in the overlay is the only thing out of (windows mouse pointer precision, overlay - focusable, and overlay - hardware acceleration) that affected the success rate positively.

Success Rate of Fast Tagging:
Overlay - Hardware Acceleration Off - 30-50%
Overlay - Hardware Acceleration Off, Focusable off - 10%
Overlay - Hardware Acceleration On (in combination with focusable/Windows pointer precision on/off) < 2%
Overlay - Hardware Acceleration On, Screen Capture LICEcap - 10%
Overlay - Hardware Acceleration On, Windows Steps Recorder - 100%

**Comment by erocheleau** [comment] 2020-04-28 16:19
I don't understand how to change the "hardware acceleration" settings in the overlay...

**Comment by mrzever** [comment] 2020-04-28 17:18
> 
> 
> I don't understand how to change the "hardware acceleration" settings in the overlay...

right click on poe overlay icon on desktop

but i don't know how to find windows steps recorder option?

**Comment by EhhNahNoMouse** [comment] 2020-04-28 17:21
![image](https://user-images.githubusercontent.com/63628669/80517304-bb7e9e00-8939-11ea-851e-f23c5d2bf6bd.png)
Is a picture of the "hardware acceleration" option in the overlay.

The way I found windows step recorder is click the windows icon and type "step", for me it shows up in the search as the top result.

**Comment by erocheleau** [comment] 2020-04-28 17:25
@EhhNahNoMouse I'm so stupid 🤦‍♂️ ... 
I just tried without the hardware acceleration on the overlay, it seems it restarts after it was disabled, and it didn't solve the issue unfortunately.

**Comment by EhhNahNoMouse** [comment] 2020-04-28 17:28
Sorry to hear that!

**Comment by erocheleau** [comment] 2020-04-28 17:34
This is made with Electron right? is the local setup easy to manage? I am a dev myself that could totally try to debug that and find out more about what is going on basically.

It was not yet annoying enough to justify a local setup haha but not it's starting to be really annoying.

**Comment by ost3g0** [comment] 2020-04-29 03:15
Still having this issue - here's a video of it going on for me.  moving the item seems to always help fix it for that specific item.  it's very strange.  

https://youtu.be/VwftHe1cl_M

**Closed** 2020-06-03 04:57 UTC
Labels: bug, wontfix
