### ISSUE TITLE
SUGGESTION: Auto Quality (20%) for items

### ISSUE THREAD

**Issue by LegoWaffle** [Kyusung4698/PoE-Overlay#363] opened 2020-03-18 19:09 UTC
Would it be possible to add a toggle to calculate item stats at 20 quality if the item is below that quality? TradeMacro had this, and would help with more accurate quick pricing (I.E. Phys DPS, Armour, Energy Shield, etc)

**Comment by Kyusung4698** [comment] 2020-03-18 19:18
Duplicate of #136

**Closed by Kyusung4698** 2020-03-18 19:18 UTC
