### ISSUE TITLE
Suggestion: Better overview for currency listings

### ISSUE THREAD

**Issue by Rottenbeer** [Kyusung4698/PoE-Overlay#569] opened 2020-04-04 22:00 UTC
# 🚀 feature request

I would love to have a nice overview of currency listings when I search for currency items.
https://i.imgur.com/x59ifU4.png
I guess 14.29 <=> 1 is the price from poe.ninja, but I want to see the other listings from the bulk search on the official trade site when pricing currency.

If you could give me a list like this:
1:16
1:15.88
1:15.53
...
This would be awesome!

Also if I click on "Open in Browser" it shows me all kinds of currency (https://i.imgur.com/7WU4NwZ.png) which is not that helpful.

I very appreciate your work on the overlay, it's awesome!

**Comment by Kyusung4698** [comment] 2020-04-04 22:30
Duplicate of #377

**Closed by Kyusung4698** 2020-04-04 22:30 UTC
Labels: enhancement
