### ISSUE TITLE
Suggestion: Support for Nvidia Now

### ISSUE THREAD

**Issue by Fittskagg** [Kyusung4698/PoE-Overlay#478] opened 2020-03-26 08:38 UTC
Would very much appreciate support for Nvidia now. ❤️

**Comment by Kyusung4698** [comment] 2020-03-26 12:27
> > Cant be done since poe overlay doesnt have access to clipboard info

> Yes, basically this. The program uses the clipboard info in order to parse the item data. NVIDIA Geforce Now does not share this information because it's not a fully functional VM. This is understandable as the core focus of their service is on performance and therefore it's highly customized to reduce network traffic. I don't think this will ever be possible.

Duplicate of #278

**Closed by Kyusung4698** 2020-03-26 12:27 UTC
Labels: enhancement
