### ISSUE TITLE
Limit reached error

### ISSUE THREAD

**Issue by lordofanatolia** [Kyusung4698/PoE-Overlay#695] opened 2020-05-09 07:51 UTC
# 🐞 bug report

**Describe the bug**
Just downloaded new update and I can't check prices anymore. It says limit reached come back later. I tried to lover fetched item count

**To Reproduce**

**Expected behavior**

**Screenshots**

## 🌍  Your Environment

- OS:  e.g. Win10 x64
- Version:  e.g. 0.6.27 
- PoE:  e.g.  3.10.0/e English

**Comment by zuekut** [comment] 2020-05-09 08:32
Getting the same error, almost every 2nd search results in that.

**Comment by Byngalo** [comment] 2020-05-09 08:39
All time that error and doesnt matter what settings u use!!! Fix that PLEASE! I Wont Use AwPoETrade!

**Comment by A6sent** [comment] 2020-05-09 14:14
Same error all the time today. It drive me crazy.
I tried to log in in eternal browser and set limit at 30 items check, but it didnt helped at all.

**Comment by Kyusung4698** [comment] 2020-05-09 19:09
## 0.6.28 (2020-05-09)

- fixed a rate limit issue which was caused by requests not getting marked as finished (#695)

**Closed** 2020-06-13 20:10 UTC
Labels: waiting for feedback, wontfix
