### ISSUE TITLE
PoE not gaining focus correctly after closing/hiding applications

### ISSUE THREAD

**Issue by barbarolucente** [Kyusung4698/PoE-Overlay#469] opened 2020-03-25 15:53 UTC
# 🐞 bug report

**Describe the bug**

After hiding or closing external application (browsers, ecc.), PoE is not gaining focus, this cause applications like Poe Trades Companion to not work until I click twice on PoE in the app bar.
**To Reproduce**

**Expected behavior**

**Screenshots**

## 🌍  Your Environment

- OS:  e.g. Win10 x64
- Version:  e.g. 0.6.12 setup
- PoE:  e.g. Steam 3.10.0/e English

**Comment by Kyusung4698** [comment] 2020-03-25 16:34
Duplicate of #460

**Closed by Kyusung4698** 2020-03-25 16:34 UTC
Labels: bug
