### ISSUE TITLE
Suggestion: Search by open prefix/suffix slots

### ISSUE THREAD

**Issue by goudekid** [Kyusung4698/PoE-Overlay#513] opened 2020-03-29 19:08 UTC
It'd be nice if there was a checkbox or something in the search UI to include the item's open suffix and prefix slots, since an item with good stats but no open slots and and item with the same stats but 3 open slots will have totally different values

**Comment by Kyusung4698** [comment] 2020-03-30 10:11
Duplicate of #409

**Closed by Kyusung4698** 2020-03-30 10:11 UTC
Labels: enhancement
